export const SIGNUP_SET_PASSWORD = 'SET_PASSWORD';
export const SIGNUP_SET_CONFIRM_PASSWORD = 'SET_CONFIRM_PASSWORD';
export const SIGNUP_SET_EMAIL = 'SET_EMAIL';
export const SIGNUP_SET_USERNAME = 'SET_USERNAME';
